rvm: '2.5.0'

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'create tablepeeps(id SERIAL PRIMARY KEY, username VARCHAR(15), message VARCHAR(140), time VARCHAR(100))");' -U postgres
  - psql -c 'create tableusers(id SERIAL PRIMARY KEY, email VARCHAR(60), name VARCHAR(15), username VARCHAR(15), password VARCHAR(20))");' -U postgres
